In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [7]:
df = pd.read_csv('finalcleandf.csv')

In [8]:
bins = [0, 25000,35000, 45000,60000,np.inf]
#names = ["-25","25-35" ,'35-45', '45-60', '60+']
names = [0,1 ,2, 3, 4,]
df['salaryclass'] = pd.cut(df['salary'], bins, labels=names).astype(int)

In [9]:
df.drop(["typeofcontract", 'iscocode','salary', 'descriptionclean'], axis=1, inplace=True)


In [10]:
one_hot=pd.get_dummies(df[['province', 'education', 'experience','iscodescription']]).astype(int)
df=df.join(one_hot)
df.drop(['province', 'education', 'experience','iscodescription'], axis=1, inplace=True)


In [12]:
df.head()

salaryclass  province_Drenthe  province_Flevoland  province_Friesland  \
0            3                 0                   0                   0   
1            2                 0                   0                   0   
2            2                 0                   0                   1   
3            2                 0                   0                   0   
4            3                 0                   0                   0   

   province_Gelderland  province_Groningen  province_Limburg  \
0                    0                   0                 0   
1                    0                   0                 0   
2                    0                   0                 0   
3                    1                   0                 0   
4                    0                   0                 0   

   province_Noord-Brabant  province_Noord-Holland  province_Overijssel  \
0                       0                       0                    0   
1                       1                       0                    0   
2                       0                       0                    0   
3                       0                       0                    0   
4                       0                       1                    0   

              ...               iscodescription_Systeembeheerders  \
0             ...                                               0   
1             ...                                               0   
2             ...                                               0   
3             ...                                               0   
4             ...                                               0   

   iscodescription_Technici op het gebied van medische dossiers en gezondheidsvoorlichting  \
0                                                  0                                         
1                                                  0                                         
2                                                  0                                         
3                                                  0                                         
4                                                  0                                         

   iscodescription_Technici voor de werking van informatie- en communicatietechnologie  \
0                                                  0                                     
1                                                  0                                     
2                                                  0                                     
3                                                  0                                     
4                                                  0                                     

   iscodescription_Technici voor informatie- en communicatietechnologie: gebruikersondersteuning  \
0                                                  0                                               
1                                                  0                                               
2                                                  0                                               
3                                                  0                                               
4                                                  1                                               

   iscodescription_Telecommunicatie-ingenieurs  \
0                                            0   
1                                            0   
2                                            0   
3                                            0   
4                                            0   

   iscodescription_Telecommunicatietechnici  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   iscodes

In [13]:
df_target=pd.DataFrame(df['salaryclass'],columns=['salaryclass'])


In [14]:
df_feat=df.drop(['salaryclass'], axis=1)
df_feat.head()

province_Drenthe  province_Flevoland  province_Friesland  \
0                 0                   0                   0   
1                 0                   0                   0   
2                 0                   0                   1   
3                 0                   0                   0   
4                 0                   0                   0   

   province_Gelderland  province_Groningen  province_Limburg  \
0                    0                   0                 0   
1                    0                   0                 0   
2                    0                   0                 0   
3                    1                   0                 0   
4                    0                   0                 0   

   province_Noord-Brabant  province_Noord-Holland  province_Overijssel  \
0                       0                       0                    0   
1                       1                       0                    0   
2                       0                       0                    0   
3                       0                       0                    0   
4                       0                       1                    0   

   province_Utrecht             ...               \
0                 0             ...                
1                 0             ...                
2                 0             ...                
3                 0             ...                
4                 0             ...                

   iscodescription_Systeembeheerders  \
0                                  0   
1                                  0   
2                                  0   
3                                  0   
4                                  0   

   iscodescription_Technici op het gebied van medische dossiers en gezondheidsvoorlichting  \
0                                                  0                                         
1                                                  0                                         
2                                                  0                                         
3                                                  0                                         
4                                                  0                                         

   iscodescription_Technici voor de werking van informatie- en communicatietechnologie  \
0                                                  0                                     
1                                                  0                                     
2                                                  0                                     
3                                                  0                                     
4                                                  0                                     

   iscodescription_Technici voor informatie- en communicatietechnologie: gebruikersondersteuning  \
0                                                  0                                               
1                                                  0                                               
2                                                  0                                               
3                                                  0                                               
4                                                  1                                               

   iscodescription_Telecommunicatie-ingenieurs  \
0                                            0   
1                                            0   
2                                            0   
3                                            0   
4                                            0   

   iscodescription_Telecommunicatietechnici  \
0                                         0   
1                                         0   
2                                         0   
3                                         0 

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df_feat, df_target, test_size=0.30, random_state=101)

In [23]:
from sklearn.svm import LinearSVC
model = LinearSVC(multi_class='ovr')
model.fit(X_train,y_train)

C:\Programfiles\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [20]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)

C:\Programfiles\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [24]:
predictions = model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[  32  175   50  179    2]
 [  18  516  378  812    7]
 [   5  286  488 1743    9]
 [   1  100  304 3051   21]
 [   2   30   39 1132   18]]


In [25]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       0.55      0.07      0.13       438
          1       0.47      0.30      0.36      1731
          2       0.39      0.19      0.26      2531
          3       0.44      0.88      0.59      3477
          4       0.32      0.01      0.03      1221

avg / total       0.42      0.44      0.36      9398



In [131]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00       438
          1       0.45      0.30      0.36      1731
          2       0.36      0.14      0.20      2531
          3       0.43      0.89      0.58      3477
          4       0.00      0.00      0.00      1221

avg / total       0.34      0.42      0.33      9398



C:\Programfiles\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
